---
title       : Plotting Predictors Application
subtitle    : Get to Your Results FAST
author      : Effi P
job         : Data Science Specialisation Track
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
---


### <font color="#CD3278"><b>WHY</b></font> have a Plotting Predictors Application?


* Easily visualise predictors from the <b>Wage</b> data
* Understanding how the data looks & how it interacts at a glance
* Quick access to a selection of the most popular plotting methods
* Switch easily between plot types and compare results


---
### <font color="#CD3278"><b>WHAT</b></font> is the Plotting Predictors Application?
* A simple application that provides a number of the most popular predictor plots
* Works on the <b>Wage</b> dataset
* Offers a selection of 5 different plot types 
* The plot types available are:
  * <b>Feature Plot (Wage)</b>: Feature plot using age, education and jobcode against wage
  * <b>Jobclass (Age vs Wage)</b>: Plot of age vs wage coloured by jobclass.
  * <b>Smoothers (Age vs Wage)</b>: Plot of age vs wage coloured by education with linear smoother for each education class
  * <b>Boxplot (Wage vs Age)</b>: Boxplot of age vs wage showing with different colours the various wage ranges
  * <b>Density Plot (Wage)</b>: Density plot of wage vs education

---
### <font color="#CD3278"><b>HOW</b></font> does the Plotting Predictors Applications Work?


* The user selects the plot type from a drop-down list
* The code for the plot is generated
* The plot appears on the right hand side of the screen
* An example of the <b>Density Plot (Wage)</b> is shown below:

```{r ,echo=FALSE,warning=FALSE, message=FALSE, fig.height=4,fig.width=6}
library (ISLR)
library(ggplot2)
data(Wage)

# Move to the working directory
setwd('C:\\epsychog\\Trainings & Events\\Data Science\\Data Science Specialisation (coursera)\\9. Developing Data Products\\Course Project')

# Call the plot funtion
p1 <- qplot(wage, colour=education, data=Wage, geom="density")
p1
```

---
<blockquote>
<center><font size=12><br><br><br><br>
The Plotting Predictor Application Rocks!</font></center>
<br>
<center> <font size=10></nl></nl></nl>It Speeds Up Your Analysis and Gets you to Your Results<br><br><br></font></center>
<center> <font color="#CD3278"><font size=16><b>FAST!!!</b></font></font></center>
</blockquote>
